import { i18n } from "#i18n";

const LANGUAGES = [
  { id: 0, label: i18n.t("languagesMatchYoutube"), opt: "youtube" },
  { id: 999, label: i18n.t("languagesMatchBrowser"), opt: "browser" },
  { id: 1, label: "Afrikaans", opt: "af" },
  { id: 2, label: "Azərbaycan", opt: "az" },
  { id: 3, label: "Bahasa Indonesia", opt: "id" },
  { id: 4, label: "Bahasa Malaysia", opt: "ms" },
  { id: 5, label: "Bosanski", opt: "bs" },
  { id: 6, label: "Català", opt: "ca" },
  { id: 7, label: "Čeština", opt: "cs" },
  { id: 8, label: "Dansk", opt: "da" },
  { id: 9, label: "Deutsch", opt: "de" },
  { id: 10, label: "Eesti", opt: "et" },
  { id: 11, label: "English (India)", opt: "en-IN" },
  { id: 12, label: "English (UK)", opt: "en-GB" },
  { id: 13, label: "English (US)", opt: "en" },
  { id: 14, label: "Español (España)", opt: "es-ES" },
  { id: 15, label: "Español (Latinoamérica)", opt: "es" },
  { id: 16, label: "Español (US)", opt: "es-US" },
  { id: 17, label: "Euskara", opt: "eu" },
  { id: 18, label: "Filipino", opt: "fil" },
  { id: 19, label: "Français", opt: "fr" },
  { id: 20, label: "Français (Canada)", opt: "fr-CA" },
  { id: 21, label: "Galego", opt: "gl" },
  { id: 22, label: "Hrvatski", opt: "hr" },
  { id: 23, label: "IsiZulu", opt: "zu" },
  { id: 24, label: "Íslenska", opt: "is" },
  { id: 25, label: "Italiano", opt: "it" },
  { id: 26, label: "Kiswahili", opt: "sw" },
  { id: 27, label: "Latviešu", opt: "lv" },
  { id: 28, label: "Lietuvių", opt: "lt" },
  { id: 29, label: "Magyar", opt: "hu" },
  { id: 30, label: "Nederlands", opt: "nl" },
  { id: 31, label: "Norsk", opt: "no" },
  { id: 32, label: "O‘zbek", opt: "uz" },
  { id: 33, label: "Polski", opt: "pl" },
  { id: 34, label: "Português (Portugal)", opt: "pt-PT" },
  { id: 35, label: "Português (Brasil)", opt: "pt" },
  { id: 36, label: "Română", opt: "ro" },
  { id: 37, label: "Shqip", opt: "sq" },
  { id: 38, label: "Slovenčina", opt: "sk" },
  { id: 39, label: "Slovenščina", opt: "sl" },
  { id: 40, label: "Srpski (Latin)", opt: "sr" },
  { id: 41, label: "Српски (Cyrillic)", opt: "sr-Cyrl" },
  { id: 42, label: "Suomi", opt: "fi" },
  { id: 43, label: "Svenska", opt: "sv" },
  { id: 44, label: "Tiếng Việt", opt: "vi" },
  { id: 45, label: "Türkçe", opt: "tr" },
  { id: 46, label: "Беларуская", opt: "be" },
  { id: 47, label: "Български", opt: "bg" },
  { id: 48, label: "Кыргызча", opt: "ky" },
  { id: 49, label: "Қазақ Тілі", opt: "kk" },
  { id: 50, label: "Македонски", opt: "mk" },
  { id: 51, label: "Монгол", opt: "mn" },
  { id: 52, label: "Русский", opt: "ru" },
  { id: 53, label: "Українська", opt: "uk" },
  { id: 54, label: "Ελληνικά", opt: "el" },
  { id: 55, label: "Հայերեն", opt: "hy" },
  { id: 56, label: "עברית", opt: "he" },
  { id: 57, label: "اردو", opt: "ur" },
  { id: 58, label: "العربية", opt: "ar" },
  { id: 59, label: "فارسی", opt: "fa" },
  { id: 60, label: "नपल", opt: "ne" },
  { id: 61, label: "मरठ", opt: "mr" },
  { id: 62, label: "हन", opt: "hi" },
  { id: 63, label: "অসময", opt: "as" },
  { id: 64, label: "বল", opt: "bn" },
  { id: 65, label: "ਪਜਬ", opt: "pa" },
  { id: 66, label: "ગજરત", opt: "gu" },
  { id: 67, label: "ଓଡଆ", opt: "or" },
  { id: 68, label: "தமழ", opt: "ta" },
  { id: 69, label: "తలగ", opt: "te" },
  { id: 70, label: "ಕನನಡ", opt: "kn" },
  { id: 71, label: "മലയള", opt: "ml" },
  { id: 72, label: "සහල", opt: "si" },
  { id: 73, label: "ภาษาไทย", opt: "th" },
  { id: 74, label: "ລາວ", opt: "lo" },
  { id: 75, label: "ဗမာ", opt: "my" },
  { id: 76, label: "ქართული", opt: "ka" },
  { id: 77, label: "አማርኛ", opt: "am" },
  { id: 78, label: "ខមរ", opt: "km" },
  { id: 79, label: "中文 (简体)", opt: "zh-CN" },
  { id: 80, label: "中文 (繁體)", opt: "zh-TW" },
  { id: 81, label: "中文 (香港)", opt: "zh-HK" },
  { id: 82, label: "日本語", opt: "ja" },
  { id: 83, label: "한국어", opt: "ko" },
] as const;

export default LANGUAGES;
